# fly.toml app configuration file generated for tvbox on 2024-02-21T15:55:32+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tvbox"
primary_region = "sin"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[checks]
  [checks.alive]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/alive"
    port = 8081
    timeout = "10s"
    type = "http"
    [checks.alive.headers]
      Content-Type = "application/json"
      Authorization = "super-secret"